name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Logout from Docker Hub
        run: docker logout

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install aws-iam-authenticator
        run: |
          curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/latest/download/aws-iam-authenticator_$(uname -s)_$(uname -m)
          chmod +x ./aws-iam-authenticator
          sudo mv ./aws-iam-authenticator /usr/local/bin/

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name my-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply --validate=false -f - <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: fastapi-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: fastapi
            template:
              metadata:
                labels:
                  app: fastapi
              spec:
                containers:
                  - name: fastapi
                    image: ${{ secrets.DOCKER_USERNAME }}/my-app:latest
                    ports:
                      - containerPort: 8000
                    env:
                      - name: AWS_ACCESS_KEY_ID
                        valueFrom:
                          secretKeyRef:
                            name: aws-secrets
                            key: AWS_ACCESS_KEY_ID
                      - name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                          secretKeyRef:
                            name: aws-secrets
                            key: AWS_SECRET_ACCESS_KEY
                      - name: AWS_REGION
                        value: ${{ secrets.AWS_DEFAULT_REGION }}
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: fastapi-service
          spec:
            type: LoadBalancer
            ports:
              - port: 80
                targetPort: 8000
            selector:
              app: fastapi
          EOF
